server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: abc123
  rabbitmq:
    host: 192.168.101.129
    port: 5673
    virtual-host: /hm-dianping
    username: hm-dianping
    password: 123
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  redisson:
    config: |
      singleServerConfig:
        address: "redis://192.168.101.129:6379"
        password: "abc123"
  data:
    redis:
      host: 192.168.101.129
      port: 6379
      password: abc123
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          # time-between-eviction-runs 属性已被移除，可以直接删除

mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
#    org.springframework.amqp: TRACE  # Spring AMQP 组件的详细日志
#    com.rabbitmq.client: DEBUG     # RabbitMQ Java 客户端库的日志 (也可以设为 TRACE)